// AUREA AI Engine - Gemini Service
// This module handles all communication with the Google Gemini API
// It must run server-side to protect the API key

import {
  SYSTEM_PROMPT,
  INTENT_ANALYSIS_PROMPT,
  PRIORITY_ASSESSMENT_PROMPT,
  DOCUMENT_ANALYSIS_PROMPT,
  TASK_GENERATION_PROMPT,
  INSIGHTS_PROMPT,
  WEEKLY_BRIEFING_PROMPT,
  CHAT_PROMPT,
} from './prompts';

import type {
  EngineConfig,
  AIResponse,
  IntentResult,
  PriorityAssessment,
  DocumentAnalysis,
  TaskGeneration,
  AIInsight,
  WeeklyBriefing,
  LifeItem,
  ChatMessage,
} from './types';

const DEFAULT_CONFIG: EngineConfig = {
  model: 'gemini-2.0-flash',
  temperature: 0.3,
  maxTokens: 4096,
};

// Format date for prompts
function getToday(): string {
  return new Date().toISOString().split('T')[0];
}

// Format items for prompt context
function formatItemsForPrompt(items: LifeItem[]): string {
  if (!items || items.length === 0) return 'No items in context.';
  return items.map(item => JSON.stringify({
    id: item.id,
    type: item.type,
    title: item.title,
    provider: item.provider,
    amount: item.amount,
    currency: item.currency,
    dueDate: item.dueDate,
    expirationDate: item.expirationDate,
    priority: item.priority,
    status: item.status,
  }, null, 2)).join('\n');
}

// Format chat history for prompt
function formatChatHistory(messages: ChatMessage[]): string {
  return messages.map(msg => `[${msg.role.toUpperCase()}]: ${msg.content}`).join('\n\n');
}

// Validate JSON response from Gemini
function validateJSONResponse<T>(raw: string, fallback: T): { data: T; valid: boolean } {
  try {
    // Try to extract JSON from the response
    const jsonMatch = raw.match(/\{[\s\S]*\}|\[[\s\S]*\]/);
    if (!jsonMatch) {
      return { data: fallback, valid: false };
    }
    const parsed = JSON.parse(jsonMatch[0]);
    return { data: parsed as T, valid: true };
  } catch {
    return { data: fallback, valid: false };
  }
}

// Core Gemini API call function
export async function callGemini(
  prompt: string,
  config: Partial<EngineConfig> = {},
  apiKey?: string
): Promise<AIResponse<string>> {
  const startTime = Date.now();
  const finalConfig = { ...DEFAULT_CONFIG, ...config };
  const key = apiKey || getApiKey();

  if (!key) {
    return {
      success: false,
      error: 'GEMINI_API_KEY is not configured. Set it in your environment variables.',
      timestamp: new Date().toISOString(),
    };
  }

  try {
    // Use the Google Generative AI REST API directly
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${finalConfig.model}:generateContent?key=${key}`;

    const requestBody = {
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        temperature: finalConfig.temperature,
        maxOutputTokens: finalConfig.maxTokens,
      },
      systemInstruction: {
        parts: [{ text: finalConfig.systemPrompt || SYSTEM_PROMPT }],
      },
    };

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errorMessage = errorData?.error?.message || `HTTP ${response.status}`;

      if (response.status === 429) {
        return {
          success: false,
          error: 'Rate limit exceeded. Please try again in a moment.',
          timestamp: new Date().toISOString(),
          processingTime: Date.now() - startTime,
        };
      }

      if (response.status === 403) {
        return {
          success: false,
          error: 'API key is invalid or does not have access to this model.',
          timestamp: new Date().toISOString(),
          processingTime: Date.now() - startTime,
        };
      }

      return {
        success: false,
        error: `Gemini API error: ${errorMessage}`,
        timestamp: new Date().toISOString(),
        processingTime: Date.now() - startTime,
      };
    }

    const data = await response.json();
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      return {
        success: false,
        error: 'No response generated by the model.',
        timestamp: new Date().toISOString(),
        processingTime: Date.now() - startTime,
      };
    }

    return {
      success: true,
      data: text,
      model: finalConfig.model,
      timestamp: new Date().toISOString(),
      processingTime: Date.now() - startTime,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';

    if (message.includes('timeout') || message.includes('aborted')) {
      return {
        success: false,
        error: 'Request timed out. Please try again.',
        timestamp: new Date().toISOString(),
        processingTime: Date.now() - startTime,
      };
    }

    return {
      success: false,
      error: `Failed to communicate with Gemini: ${message}`,
      timestamp: new Date().toISOString(),
      processingTime: Date.now() - startTime,
    };
  }
}

// Get API key from environment (server-side only)
function getApiKey(): string | undefined {
  // In server context, use process.env
  if (typeof process !== 'undefined' && process.env?.GEMINI_API_KEY) {
    return process.env.GEMINI_API_KEY;
  }
  return undefined;
}

// ============================================
// HIGH-LEVEL ENGINE METHODS
// ============================================

export async function understandInput(
  input: string,
  context?: LifeItem[],
  apiKey?: string
): Promise<AIResponse<IntentResult>> {
  const prompt = INTENT_ANALYSIS_PROMPT
    .replace('{input}', input)
    .replace('{context}', context ? `CURRENT CONTEXT:\n${formatItemsForPrompt(context)}` : '')
    .replace('{today}', getToday());

  const result = await callGemini(prompt, { temperature: 0.2 }, apiKey);

  if (!result.success) {
    return { ...result, data: undefined };
  }

  const { data, valid } = validateJSONResponse<IntentResult>(result.data!, {
    intent: input,
    category: 'general',
    entities: [],
    confidence: 0.5,
  });

  return {
    ...result,
    data,
    error: valid ? undefined : 'Response parsing had low confidence. Data may be incomplete.',
  };
}

export async function assessPriority(
  item: LifeItem,
  allItems?: LifeItem[],
  apiKey?: string
): Promise<AIResponse<PriorityAssessment>> {
  const prompt = PRIORITY_ASSESSMENT_PROMPT
    .replace('{item}', JSON.stringify(item, null, 2))
    .replace('{allItems}', allItems ? `ALL ITEMS FOR CONTEXT:\n${formatItemsForPrompt(allItems)}` : '')
    .replace('{today}', getToday());

  const result = await callGemini(prompt, { temperature: 0.1 }, apiKey);

  if (!result.success) {
    return { ...result, data: undefined };
  }

  const { data } = validateJSONResponse<PriorityAssessment>(result.data!, {
    itemId: item.id,
    priority: 'medium',
    reasons: ['Unable to parse priority assessment'],
    urgencyScore: 50,
    financialImpact: 0,
    timeSensitivity: 50,
  });

  return { ...result, data: { ...data, itemId: item.id } };
}

export async function analyzeDocument(
  content: string,
  type?: string,
  apiKey?: string
): Promise<AIResponse<DocumentAnalysis>> {
  const prompt = DOCUMENT_ANALYSIS_PROMPT
    .replace('{content}', content)
    .replace('{type}', type || 'unknown');

  const result = await callGemini(prompt, { temperature: 0.1, maxTokens: 2048 }, apiKey);

  if (!result.success) {
    return { ...result, data: undefined };
  }

  const { data, valid } = validateJSONResponse<DocumentAnalysis>(result.data!, {
    type: 'document',
    title: 'Unknown Document',
    provider: '',
    amount: 0,
    currency: 'USD',
    dueDate: '',
    expirationDate: '',
    summary: 'Unable to analyze document.',
    recommendedAction: 'Please review manually.',
    confidence: 0,
    extractedEntities: [],
  });

  return {
    ...result,
    data,
    error: valid ? undefined : 'Document analysis had low confidence.',
  };
}

export async function generateTasks(
  input: string,
  context?: LifeItem[],
  apiKey?: string
): Promise<AIResponse<TaskGeneration[]>> {
  const prompt = TASK_GENERATION_PROMPT
    .replace('{input}', input)
    .replace('{context}', context ? `CURRENT ITEMS:\n${formatItemsForPrompt(context)}` : '')
    .replace('{today}', getToday());

  const result = await callGemini(prompt, { temperature: 0.3 }, apiKey);

  if (!result.success) {
    return { ...result, data: undefined };
  }

  const { data } = validateJSONResponse<TaskGeneration[]>(result.data!, []);

  return { ...result, data: Array.isArray(data) ? data : [] };
}

export async function getInsights(
  items: LifeItem[],
  apiKey?: string
): Promise<AIResponse<AIInsight[]>> {
  const prompt = INSIGHTS_PROMPT
    .replace('{items}', formatItemsForPrompt(items))
    .replace('{today}', getToday());

  const result = await callGemini(prompt, { temperature: 0.4, maxTokens: 4096 }, apiKey);

  if (!result.success) {
    return { ...result, data: undefined };
  }

  const { data } = validateJSONResponse<AIInsight[]>(result.data!, []);

  return { ...result, data: Array.isArray(data) ? data : [] };
}

export async function generateWeeklyBriefing(
  items: LifeItem[],
  apiKey?: string
): Promise<AIResponse<WeeklyBriefing>> {
  const prompt = WEEKLY_BRIEFING_PROMPT
    .replace('{items}', formatItemsForPrompt(items))
    .replace('{today}', getToday());

  const result = await callGemini(prompt, { temperature: 0.4, maxTokens: 4096 }, apiKey);

  if (!result.success) {
    return { ...result, data: undefined };
  }

  const { data } = validateJSONResponse<WeeklyBriefing>(result.data!, {
    period: { start: getToday(), end: getToday() },
    summary: 'Unable to generate briefing.',
    criticalItems: [],
    upcomingDeadlines: [],
    financialOverview: { totalDue: 0, currency: 'USD', breakdown: [] },
    insights: [],
    recommendedActions: [],
  });

  return { ...result, data };
}

export async function chat(
  messages: ChatMessage[],
  context?: LifeItem[],
  apiKey?: string
): Promise<AIResponse<string>> {
  const prompt = CHAT_PROMPT
    .replace('{history}', formatChatHistory(messages))
    .replace('{context}', context ? formatItemsForPrompt(context) : 'No items in context.')
    .replace('{today}', getToday());

  return callGemini(prompt, { temperature: 0.5 }, apiKey);
}

// Export the engine interface
export const geminiService = {
  callGemini,
  understandInput,
  assessPriority,
  analyzeDocument,
  generateTasks,
  getInsights,
  generateWeeklyBriefing,
  chat,
};

export default geminiService;
